services:
  - type: worker
    name: xsistem-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python xsistem_bot.py
    envVars:
      - key: 8087735462:AAGII-XvO3hJy3YgDd3b0vjiIHjnQCn4Ej4
        sync: false
      - key: ADMIN_CHAT_ID
        value: 5720343562
