services:
  - type: worker
    name: xsistem-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python xsistem_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_CHAT_ID
        value: 5720343562
